import { describe, expect, it } from "vitest";
import {
  isBaiduStreetViewTuxunLocation,
  isGoogleStreetViewTuxunLocation,
  type TuxunLocation,
} from "./tuxun-locations";

const baseLocation: TuxunLocation = {
  id: "test-location",
  title: "测试地点",
  province: "测试省",
  city: "测试市",
  lat: 30,
  lng: 120,
  heading: 0,
  pitch: 0,
  hint: "测试提示",
};

describe("isBaiduStreetViewTuxunLocation", () => {
  it("only accepts locations generated by the Baidu panorama service", () => {
    expect(
      isBaiduStreetViewTuxunLocation({
        ...baseLocation,
        source: "baidu-random",
      }),
    ).toBe(true);

    expect(
      isBaiduStreetViewTuxunLocation({
        ...baseLocation,
        source: "fallback",
      }),
    ).toBe(false);

    expect(isBaiduStreetViewTuxunLocation(baseLocation)).toBe(false);
  });
});

describe("isGoogleStreetViewTuxunLocation", () => {
  it("only accepts locations generated by the Google street view service", () => {
    expect(
      isGoogleStreetViewTuxunLocation({
        ...baseLocation,
        source: "google-random",
      }),
    ).toBe(true);

    expect(
      isGoogleStreetViewTuxunLocation({
        ...baseLocation,
        source: "baidu-random",
      }),
    ).toBe(false);

    expect(isGoogleStreetViewTuxunLocation(baseLocation)).toBe(false);
  });
});
